# Generated by Django 3.2.16 on 2023-04-10 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='1200x-1.jpeg', upload_to='profile_pics'),
        ),
    ]
