# Generated by Django 3.2.16 on 2023-04-10 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imges',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
