# Generated by Django 3.2.16 on 2023-04-19 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_imges'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='1200x-1.jpeg', upload_to='profile_pics'),
        ),
    ]
