# Generated by Django 3.2.16 on 2023-04-19 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='imges',
        ),
    ]
