# Generated by Django 3.2.16 on 2023-05-03 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy_product', '0003_addproduct2_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproduct2',
            name='price',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
