# Generated by Django 3.2.16 on 2023-05-12 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy_product', '0004_alter_addproduct2_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='test_t',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=50)),
            ],
        ),
    ]
