# Generated by Django 3.2.16 on 2023-05-12 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy_product', '0005_test_t'),
    ]

    operations = [
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('size', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
