# Generated by Django 3.2.16 on 2023-05-16 17:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('buy_product', '0007_land_operationg'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproduct2',
            name='date_posted_product',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='land',
            name='operationg',
            field=models.CharField(blank=True, choices=[('Home', 'Home'), ('Land', 'Land'), ('Apartmnet', 'Apartment')], max_length=30, null=True),
        ),
    ]
